apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: accountownerapp-api
spec:
  replicas: 1
  paused: true
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: accountownerapp-api
    spec:
      containers:
      - name: accountownerapp-api
        image: accountownerapp
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: DB
          value: "db"
---
apiVersion: v1
kind: Service
metadata:
  name: accountownerapp-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: accountownerapp-front